# Calibration parameters - Saved at: 2025-04-09 03:46:24
# Camera parameter settings
camera:
  width: 640          # Image width (pixels)
  height: 480         # Image height (pixels)
  fov: 56.0           # Field of View - degrees
  x: 0.45              # Vehicle-frame X position (meters)
  y: 0.21              # Vehicle-frame Y position (meters)
  z: 1.42              # Vehicle-frame Z position (meters)
  roll: 0           # Roll angle (radians) - X-axis rotation
  pitch: -0          # Pitch angle (radians) - Y-axis rotation
  yaw: -0            # Yaw angle (radians) - Z-axis rotation

# LiDAR parameter settings
lidar:
  x: 1.30              # Vehicle-frame X position (meters)
  y: 0.01              # Vehicle-frame Y position (meters)
  z: 1.03             # Vehicle-frame Z position (meters)
  roll: 0           # Roll angle (radians) - X-axis rotation
  pitch: 0          # Pitch angle (radians) - Y-axis rotation
  yaw: 0           # Yaw angle (radians) - Z-axis rotation
